version: '3.7'

services:

  mysql:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /Users/shamskhalil/Desktop/compose/STORAGE/mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kasudb
    networks:
      - mynet

  mgdb:
    image: mongo
    restart: always
    volumes:
      - /Users/shamskhalil/Desktop/compose/STORAGE/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - mynet

networks:
  mynet:
